### PR TITLE
Update tools.rst

### PR DESCRIPTION
**Pull request by ravishk17**

### CODE REVIEW

**Comment by dougburks** [comment]
Hi @ravishk17 ,

Thanks for the PR, but what exactly are you changing here and why?

**Comment by ravishk17** [comment]
A small spelling error was there.
Changed "thru" to "through".
"thru" is a non-standard spelling of "through"

**Comment by dougburks** [comment]
That's a direct quote from https://www.tldp.org/LDP/Linux-Dictionary/html/n.html so, if you change it, it is no longer a direct quote.

How about we change that section to quote from the following instead?
http://manpages.ubuntu.com/manpages/xenial/man1/netsed.1.html

```
netsed is a small and handy utility to alter, in real time, the contents of packets
forwarded in a network stream, or in a datagram connection. When called with a set of
replacement rules, these rules are tested for applicability to each packet entering in
either direction.
```

**Comment by ravishk17** [comment]
In my opinion the current quote is better.

The current one is very much explanatory and easy to understand compared to the one you proposed.

**Comment by dougburks** [comment]
In that case, we'll leave it as-is with no changes.

**Pull request closed without merging**
