### PR TITLE
PR into 2.4 for AU Security Onion Analyzers project

### PR DESCRIPTION
**Pull request by semphorin**
Updated cases.rst to include the four analyzers the AU Security Onion capstone team has developed.

### CODE REVIEW

**Comment by HoangLongVu** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by semphorin** [comment]
recheck

**Comment by Xelial-1064** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by semphorin** [comment]
recheck

**Comment by HoangLongVu** [comment]
**I have read the CLA Document and I hereby sign the CLA**

> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://securityonionsolutions.com/cla) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **0** out of **2** committers have signed the CLA.❌ @HoangLongVu❌ @Xelial-1064You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Pull request closed without merging**
